services:
  _defaults:
    autowire: true
    public: false

  Tellaw\SunshineAdminBundle\Service\:
    resource: '../../Service'
    exclude: '../../Service/AbstractWidget.php'

  Tellaw\SunshineAdminBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Tellaw\SunshineAdminBundle\Service\MenuService:
    arguments:
      $configuration: "%tellaw_sunshine_admin.menu%"
      $entityConfiguration: "%tellaw_sunshine_admin.entities%"

  Tellaw\SunshineAdminBundle\Service\PageService:
    arguments:
      $configuration: "%tellaw_sunshine_admin.pages%"

  Tellaw\SunshineAdminBundle\Service\EntityService:
    arguments:
      $configuration: "%tellaw_sunshine_admin.entities%"

  Tellaw\SunshineAdminBundle\Service\ThemeService:
    arguments:
      $configuration: "%tellaw_sunshine_admin.theme%"

  Tellaw\SunshineAdminBundle\Twig\WidgetExtension:
    arguments:
      $configuration: "%tellaw_sunshine_admin.pages%"
    tags:
      - { name: twig.extension }

  Tellaw\SunshineAdminBundle\Twig\CollectionExtension:
    tags:
      - { name: twig.extension }

  Tellaw\SunshineAdminBundle\Twig\MenuExtension:
    tags:
      - { name: twig.extension }

  Tellaw\SunshineAdminBundle\Form\Type\DefaultType:
    tags:
      - { name: form.type }

  Tellaw\SunshineAdminBundle\Form\Type\FiltersType:
    tags:
      - { name: form.type }

  ##
  ## WIDGETS DEFINITION
  ##
  Tellaw\SunshineAdminBundle\Service\Widgets\EditWidget:
    tags:
      - {name: sunshine.widget }

  Tellaw\SunshineAdminBundle\Service\Widgets\ViewWidget:
    tags:
      - {name: sunshine.widget }

  Tellaw\SunshineAdminBundle\Service\Widgets\ListWidget:
    tags:
      - {name: sunshine.widget }

  Tellaw\SunshineAdminBundle\Twig\ThemeExtension:
    public: true
    arguments: ["%tellaw_sunshine_admin.theme%"]
    tags:
      - { name: twig.extension }

  Tellaw\SunshineAdminBundle\Form\Type\Select2Type:
    tags:
      - form.type