services:
  sunshine.crud_service:
    class: Tellaw\SunshineAdminBundle\Service\CrudService
    arguments: ["@doctrine.orm.entity_manager", "@sunshine.entities"]

  sunshine.menu:
    class: Tellaw\SunshineAdminBundle\Service\MenuService
    arguments: ["%tellaw_sunshine_admin.menu%", "%tellaw_sunshine_admin.entities%"]

  sunshine.pages:
    class: Tellaw\SunshineAdminBundle\Service\PageService
    arguments: ["%tellaw_sunshine_admin.pages%"]

  sunshine.entities:
    class: Tellaw\SunshineAdminBundle\Service\EntityService
    arguments: ["%tellaw_sunshine_admin.entities%"]

  sunshine.widgets:
    class: Tellaw\SunshineAdminBundle\Service\WidgetService
    arguments: [ '@router' ]
    scope: request_stack
    calls:
      - [ setContainer,[ '@service_container' ] ]

  sunshine.widget_twig_extension:
    class: Tellaw\SunshineAdminBundle\Twig\WidgetExtension
    arguments: ["%tellaw_sunshine_admin.pages%", "@sunshine.widgets"]
    tags:
      - { name: twig.extension }

  sunshine.defaultType:
    class: Tellaw\SunshineAdminBundle\Form\Type\DefaultType
    arguments: ["@sunshine.crud_service"]

  sunshine.menu_twig_extension:
    class: Tellaw\SunshineAdminBundle\Twig\MenuExtension
    tags:
      - { name: twig.extension }

  sunshine.default_form_type:
    class: Tellaw\SunshineAdminBundle\Form\Type\DefaultType
    arguments: ['@sunshine.crud_service']
    tags:
      - { name: form.type }

  sunshine.widgets.edit:
    class: Tellaw\SunshineAdminBundle\Service\Widgets\EditWidget
    arguments: [ '@router', '@request_stack', '@twig' ]
    scope: request_stack
